<a href="https://colab.research.google.com/github/kartiksharma2383/E-Commerce-Order-Management-System-project-in-OOP-S-Python-/blob/main/E_Commerce_Order_Management_System_project_in_OOP'S(Python).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [120]:
import pandas as pd
import numpy as np

In [121]:
df = pd.read_csv("/content/E-commerce data(OOPS project dataset).csv", encoding = 'latin-1')
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France

In [122]:
class Customer:
  def __init__(self, CustomerID: float, Country: str):
    self.CustomerID = CustomerID
    self.Country = Country

class Product:
  def __init__(self, StockCode: str, Description: str):
    self.StockCode = StockCode
    self.Description = Description

class Order:
  def __init__(self, InvoiceNo: str, InvoiceDate: str, UnitPrice: float, Quantity: float, CustomerID: float, StockCode: str):
    self.InvoiceNo = InvoiceNo
    self.InvoiceDate = InvoiceDate
    self.UnitPrice = UnitPrice
    self.Quantity = Quantity
    self.CustomerID = CustomerID
    self.StockCode = StockCode

customers = []
for customer_id, country in df[['CustomerID', 'Country']].drop_duplicates().dropna().values:
  customers.append(Customer(customer_id, country))

products = []
for stock_code, description in df[['StockCode', 'Description']].drop_duplicates().dropna().values:
  products.append(Product(stock_code, description))

orders = []
for index, row in df.dropna().iterrows():
  orders.append(Order(row['InvoiceNo'], row['InvoiceDate'], row['UnitPrice'], row['Quantity'], row['CustomerID'], row['StockCode']))

In [123]:
class Customer:
  def __init__(self, CustomerID: float, Country: str):
    self.CustomerID = CustomerID
    self.Country = Country

def get_customer_info(self):
  return f"CustomerID: {self.CustomerID}, country: {self.Country}"

class Product:
  def __init__(self, StockCode: str, Description: str):
    self.StockCode = StockCode
    self.Description = Description

  def get_customer_info(self):
    return f"CustomerID: {self.CustomerID}, Country: {self.Country}"

In [124]:
class DiscountOrder(Order):
  def __init__(self, InvoiceNo: str, InvoiceDate: str, UnitPrice: float, Quantity: float, CustomerID: float, StockCode: str, discount_amount: float):
    super().__init__(InvoiceNo, InvoiceDate, UnitPrice, Quantity, CustomerID, StockCode)
    self.discount_amount = discount_amount

  def calculate_total_price(self):
    original_price = super().calculate_total_price()
    return original_price * (1 - self.discount_amount)

In [125]:
from abc import ABC, abstractmethod
class BaseOrder(ABC):
  @abstractmethod
  def calculate_total_price(self):
    pass

class Order(BaseOrder):
  def __init__(self, InvoiceNo: str, InvoiceDate: str, UnitPrice: float, Quantity: float, CustomerID: float, StockCode: str):
    self.InvoiceNo = InvoiceNo
    self.InvoiceDate = InvoiceDate
    self.UnitPrice = UnitPrice
    self.Quantity = Quantity
    self.CustomerID = CustomerID
    self.StockCode = StockCode

  def calculate_total_price(self) -> float:
    return self.Quantity * self.UnitPrice

class DiscountOrder(Order):
  def __init__(self, InvoiceNo: str, InvoiceDate: str, UnitPrice: float, Quantity: float, CustomerID: float, StockCode: str, discount_amount: float):
    super().__init__(InvoiceNo, InvoiceDate, UnitPrice, Quantity, CustomerID, StockCode)
    self.discount_amount = discount_amount

  def calculate_total_price(self) -> float:
    original_price = super().calculate_total_price()
    return original_price * (1 - self.discount_amount)

In [126]:
class CustomerOrderIterator:
  def __init__(self, orders_list):
    self._orders_list = orders_list
    self._index = 0

  def __iter__(self):
    return self

  def __next__(self):
    if self._index < len(self._orders_list):
      result = self._orders_list[self._index]
      self._index += 1
      return result
    else:
      raise StopIteration

sample_orders = [
    Order("INV001", "2023-10-26", 10.0, 2.0, 12345.0, "PROD001"),
    Order("INV002", "2023-10-26", 15.0, 1.0, 12345.0, "PROD002"),
    Order("INV003", "2023-10-27", 5.0, 3.0, 67890.0, "PROD003"),
]
order_iterator = CustomerOrderIterator(sample_orders)
print("iterating through orders:")
for order in order_iterator:
  print(f"Invoice No: {order.InvoiceNo}, Total Price: {order.calculate_total_price():.2f}")

iterating through orders:
Invoice No: INV001, Total Price: 20.00
Invoice No: INV002, Total Price: 15.00
Invoice No: INV003, Total Price: 15.00

In [127]:
import functools
from abc import ABC, abstractmethod

def log_order_processing(func):
    @functools.wraps(func)
    def wrapper(*args, **kwargs):
        print(f"Processing order: {args[0].InvoiceNo}")
        result = func(*args, **kwargs)
        print(f"Finished processing order: {args[0].InvoiceNo}")
        return result
    return wrapper

class BaseOrder(ABC):
    @abstractmethod
    def calculate_total_price(self) -> float:
        pass

class Order(BaseOrder):
    def __init__(self, InvoiceNo: str, InvoiceDate: str, UnitPrice: float, Quantity: float, CustomerID: float, StockCode: str):
        self.InvoiceNo = InvoiceNo
        self.InvoiceDate = InvoiceDate
        self.UnitPrice = UnitPrice
        self.Quantity = Quantity
        self.CustomerID = CustomerID
        self.StockCode = StockCode

    @log_order_processing
    def calculate_total_price(self) -> float:
        return self.Quantity * self.UnitPrice

class DiscountedOrder(Order):
    def __init__(self, InvoiceNo: str, InvoiceDate: str, UnitPrice: float, Quantity: float, CustomerID: float, StockCode: str, discount_amount: float):
        super().__init__(InvoiceNo, InvoiceDate, UnitPrice, Quantity, CustomerID, StockCode)
        self.discount_amount = discount_amount

    @log_order_processing
    def calculate_total_price(self) -> float:
        original_price = super().calculate_total_price()
        return original_price * (1 - self.discount_amount)

# Demonstrate the decorator
sample_order = Order("536365", "12/1/2010 8:26", 2.55, 6.0, 17850.0, "85123A")
sample_order.calculate_total_price()

sample_discounted_order = DiscountedOrder("536365", "12/1/2010 8:26", 2.55, 6.0, 17850.0, "85123A", 0.1)
sample_discounted_order.calculate_total_price()

Processing order: 536365
Finished processing order: 536365
Processing order: 536365
Processing order: 536365
Finished processing order: 536365
Finished processing order: 536365

13.77